-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tb_campus
(
    id serial NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    city character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_campus_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_category
(
    id serial NOT NULL,
    name_category character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_category_objeto
(
    tb_category_id integer NOT NULL,
    tb_objeto_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tb_notification
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    messager character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tb_notification_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_object
(
    id serial NOT NULL,
    name_objetct character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    status character(1) COLLATE pg_catalog."default",
    location_found character varying(255) COLLATE pg_catalog."default",
    object_image text COLLATE pg_catalog."default",
    registered_object integer NOT NULL,
    removed_by integer,
    campus_id integer NOT NULL,
    create_at date,
    update_at date,
    CONSTRAINT tb_objeto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_user
(
    id serial NOT NULL,
    user_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    password_hash character varying(255) COLLATE pg_catalog."default",
    campus_id integer NOT NULL,
    update_at timestamp with time zone,
    create_at timestamp with time zone NOT NULL DEFAULT NOW(),
    registration character varying(50) NOT NULL DEFAULT NOW(),
    CONSTRAINT tb_user_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.tb_category_objeto
    ADD CONSTRAINT fk_cat_obj_category FOREIGN KEY (tb_category_id)
    REFERENCES public.tb_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tb_category_objeto
    ADD CONSTRAINT fk_cat_obj_objeto FOREIGN KEY (tb_objeto_id)
    REFERENCES public.tb_object (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tb_notification
    ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id)
    REFERENCES public.tb_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tb_object
    ADD CONSTRAINT fk_objeto_campus FOREIGN KEY (campus_id)
    REFERENCES public.tb_campus (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tb_object
    ADD CONSTRAINT fk_objeto_registered FOREIGN KEY (registered_object)
    REFERENCES public.tb_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tb_object
    ADD CONSTRAINT fk_objeto_removed FOREIGN KEY (removed_by)
    REFERENCES public.tb_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tb_user
    ADD CONSTRAINT fk_user_campus FOREIGN KEY (campus_id)
    REFERENCES public.tb_campus (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;